#!/usr/bin/env python3
"""Generate embedded Noto Sans CJK SC Medium glyphs (requires Pillow).

Download the official NotoSansCJKsc-Medium.otf and pass its path as the argument.
The SHA-256 check pins version 2.004. No font or Python is needed at runtime.
"""

import argparse
import difflib
import hashlib
from pathlib import Path
import subprocess
import zlib

from PIL import Image, ImageDraw, ImageFont

FONT_URL = "https://raw.githubusercontent.com/notofonts/noto-cjk/main/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Medium.otf"
FONT_SHA256 = "ca094f6b0001fb048ca39ddd797a0cdb0179e1e55c6561e111c49c3e6a61d7b7"
BITMAP_SIZE = 64


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("font", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if hashlib.sha256(args.font.read_bytes()).hexdigest() != FONT_SHA256:
        parser.error("expected the official Noto Sans CJK SC Medium version 2.004")

    characters = []
    for high in range(0xB0, 0xD8):
        for low in range(0xA1, 0xFF):
            try:
                character = bytes((high, low)).decode("gb2312")
            except UnicodeDecodeError:
                continue
            if "\u4e00" <= character <= "\u9fff":
                characters.append(character)
    assert len(characters) == 3755

    font = ImageFont.truetype(str(args.font), 60)
    raw = bytearray()
    for character in characters:
        bitmap = Image.new("L", (BITMAP_SIZE, BITMAP_SIZE), 0)
        draw = ImageDraw.Draw(bitmap)
        left, top, right, bottom = draw.textbbox((0, 0), character, font=font)
        origin = ((BITMAP_SIZE - (right - left)) // 2 - left,
                  (BITMAP_SIZE - (bottom - top)) // 2 - top)
        draw.text(origin, character, font=font, fill=255)
        raw.extend(bitmap.tobytes())

    data = zlib.compress(raw, 9).hex()
    lines = "\n".join(data[i:i + 120] for i in range(0, len(data), 120))
    source = f'''// Code generated by scripts/generate-captcha-glyphs.py; DO NOT EDIT.
// Font: Noto Sans CJK SC Medium, version 2.004 (NotoSansCJKsc-Medium.otf).
// Source: {FONT_URL}
// Font SHA-256: {FONT_SHA256}
// Copyright 2014-2021 Adobe. SIL OFL 1.1; see /POINT_CAPTCHA_FONT_LICENSE.txt.
// 3,755 GB2312 level-one characters; 64x64, 8-bit grayscale coverage.

package auth

const (
    pointCaptchaChineseBitmapSize = {BITMAP_SIZE}
    pointCaptchaChineseBitmapBytes = pointCaptchaChineseBitmapSize * pointCaptchaChineseBitmapSize
    pointCaptchaChineseGlyphSet = "{''.join(characters)}"
    pointCaptchaChineseBitmapData = `{lines}`
)
'''
    source = subprocess.run(["gofmt"], input=source, text=True,
                            capture_output=True, check=True).stdout
    target = (Path(__file__).resolve().parents[1] / "{{ .Project }}" /
              "internal/modules/auth/captcha_chinese_data.go")
    before = target.read_text() if target.exists() else ""
    if source == before:
        print(f"unchanged {target}")
        return
    if args.check:
        raise SystemExit(f"glyph data differs: {target}")
    if before:
        print("".join(difflib.unified_diff(before.splitlines(True), source.splitlines(True),
                                         fromfile=str(target), tofile=str(target))), end="")
    else:
        print(f"create {target}")
    target.write_text(source)
    print(f"{len(characters)} glyphs, {len(raw)} raw bytes, {len(data) // 2} compressed bytes")


if __name__ == "__main__":
    main()
